= Antora README

== Description

From https://docs.antora.org/antora/latest/[the Antora Docs]:

[quote]
--
Antora Documentation

The Static Site Generator for Tech Writers

This site hosts the technical documentation for Antora. Antora makes it easy
for tech writers to create documentation and publish it to the web. As a tech
writer, you focus on authoring content in AsciiDoc, Antora’s content markup
language. You organize those files into a standard project structure and store
them in one or more content (git) repositories. Antora picks up your content
from there and transforms it into a website. That’s all there is to it!
--

== High level steps

To initiate the install, run `./script.sh`.  It is known to work with the following bases:

. (none)

== Technical steps

Within mingw64:

. Ensure a local nvm is installed.
. Install a correct node version
. Update system packages (e.g. `pacman -Sy`) (maybe?)
. Run instructions found https://docs.antora.org/antora/latest/install-and-run-quickstart/[here].
. Output instructions to run Antora.
